-- AlterTable
ALTER TABLE "quotes" ADD COLUMN     "cabinet_cost" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "labor_cost" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "other_costs" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "profit" DECIMAL(10,2) NOT NULL DEFAULT 0;
