-- AlterTable
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "installation_fee" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "misc_expenses" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "msrp_total" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "client_cabinet_price" DECIMAL(10,2) NOT NULL DEFAULT 0;
